server:
  servlet:
    context-path: /bookswap
  port: 9000

spring:
  datasource:
#    url: jdbc:mysql://localhost:3308/book_swap
#    username: root
#    password: 1234
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3308}/book_swap
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
      oauth2:
        resource-server:
          jwt:
            jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
            issuer-uri: https://securetoken.google.com/bookswapplatform
  mvc:
    view:
      prefix: forward:/nonexistent

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans=true:
#  profiles:
#    active: development
#Swagger
#http://localhost:9000/bookswap/swagger-ui/index.html
springdoc:
  swagger-ui:
    tags-sorter: method
    operations-sorter: method
    path: /swagger-ui.html

  paths-to-exclude: /authorities/**, /books/**, /orderses/**, /profile/**,
    /roles/**, /users/**, /authors/**, /bookImages/**, /mainCategories/**,
    /postStatuses/**, /posts/**, /areas/**, /districts/**, /orderDetails/**, 
    /payments/**, /transactions/**, /userWallets/**, /rates/**, /rateCards/**,
    /savedPosts/**, /chatRooms/**, /messages/**, /cancelOrderHistories/**, /orderShippings/**, /systemLogs/**, /bookSystems/**, /notifications/**
google:
  api:
    key: AIzaSyBJAbBCH2w3aHD_hjBhz03kUEurN0NBaMY
